[build-system]
requires = ["setuptools >= 61.0", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "pycine-lite"
authors = [
    { name = "Ben Hagen", email = "ben@ottomatic.io" },
    { name = "Takeshi (Kesh) Ikuma", email = "tikuma@lsuhsc.edu" },
]
description = "Handle .cine files created by Vision Research Phantom® cameras"
readme = "README.md"
license = { text = "LGPL-3.0 License" }
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Operating System :: OS Independent",
]
dynamic = ["version"]
requires-python = ">=3.9"
dependencies = ["numpy"]

[project.urls]
Repository = "https://github.com/tikuma-lsuhsc/pycine-lite"

[tool.setuptools.dynamic]
version = { attr = "pycine.__version__" }

[tool.black]
line-length = 120
